-- Phase 8 Part 6 — admin booking reversals (SPEC §4.4, §7.3, §7.6, §7.11; DECISIONS,
-- "Phase 8 Part 6"). Generated by drizzle-kit from src/db/schema/enums.ts.
--
-- earning_reversal: a force-cancel taking back a tutor's released earnings that
--   are still in their wallet (debit, reference = the booking, once).
-- purchase_reversal: a PayPal refund taking back the credits its payment minted
--   (debit, reference = the payment, once).
-- reversed: a tutor_earnings row a force-cancel cancelled. release-earnings only
--   claims `held`, so a reversed row is never paid.
--
-- ADD VALUE only; nothing in this migration uses the new values, so running it
-- inside the migrator's transaction is safe.
ALTER TYPE "public"."credit_transaction_type" ADD VALUE 'earning_reversal';--> statement-breakpoint
ALTER TYPE "public"."credit_transaction_type" ADD VALUE 'purchase_reversal';--> statement-breakpoint
ALTER TYPE "public"."earning_status" ADD VALUE 'reversed';